import type { MissionGapAnalysisWorkspace } from "./types"

export function getMockGapAnalysisWorkspace(): MissionGapAnalysisWorkspace {
  return {
    mission: "womanhood",
    missionTitle: "Research Mission 001 - Womanhood",
    gapCount: 9,
    assetDeficit: 12,
    missingFrameworkCount: 4,
    missingCreatorAssets: 2,
    missingTeachings: 1,
    missingExecutiveAssets: 2,
    missingAgencyAssets: 2,
    missingKnowledgeAssets: 1,
    unusedDiscoveries: 1,
    unansweredQuestions: 3,
    coverageScore: 57,
    maturityScore: 48,
    priorityScore: 82,
    recommendationScore: 76,
    healthScore: 61,
    recommendationCount: 6,
    weakestWorkspace: { workspace: "creator", score: 48, status: "weak" },
    lowMaturityAreas: ["creator", "executive", "agency"],
    missingAssets: [
      "taxonomy.md",
      "podcast-series.md",
      "interactive-course.md",
      "teaching-outline-advanced.md",
      "executive-scorecard.md",
      "agency-workshop-kit.md",
    ],
    knowledgeGaps: [
      {
        id: "gap-1",
        category: "missing-framework",
        title: "No taxonomy.md relationships",
        description: "Knowledge organization is incomplete.",
        severity: "high",
        suggestedAsset: "taxonomy.md",
        suggestedAction: "Create taxonomy.md to normalize mission terms.",
      },
    ],
    recommendations: [
      "Create taxonomy.md",
      "Promote unused discovery to creator article",
      "Build agency seminar packaging",
    ],
    timeline: [
      { date: "2026-07-05", event: "Inference gaps detected", status: "completed" },
      { date: "2026-07-06", event: "Query-based deficits mapped", status: "completed" },
      { date: "2026-07-06", event: "Gap analysis baseline generated", status: "planned" },
    ],
    readOnly: true,
    previewOnly: true,
    noAuth: true,
    noSessions: true,
    noJwt: true,
    noDatabase: true,
    noExecution: true,
    noPublishing: true,
    noOpenAI: true,
    noGraphWrites: true,
    noSocialPosting: true,
  }
}
