import type { KnowledgeIntelligenceWorkspace } from "./types"

export function getMockKnowledgeIntelligenceWorkspace(): KnowledgeIntelligenceWorkspace {
  return {
    id: "womanhood",
    name: "Knowledge Intelligence Layer",
    missionTitle: "Research Mission 001 — Womanhood",
    status: "active",
    confidence: "high",
    intelligenceScore: 74,
    knowledgeHealthScore: 68,
    brainHealthScore: 71,
    missionCount: 1,
    workspaceCount: 8,
    signalCount: 14,
    insightCount: 8,
    patternCount: 6,
    recommendationCount: 7,
    timelineCount: 6,
    discoveryCount: 12,
    assetCount: 55,
    frameworkCount: 8,
    questionCount: 8,
    teachingCount: 22,
    courseCount: 8,
    presentationCount: 5,
    decisionCount: 3,
    promptCount: 14,
    crossReferenceCount: 28,
    coverageCount: 8,
    researchCoverage: 62,
    creatorCoverage: 48,
    ministryCoverage: 60,
    executiveCoverage: 51,
    agencyCoverage: 51,
    knowledgeCoverage: 51,
    overallScore: 58,
    knowledgeDomains: ["research", "creator", "ministry", "executive", "agency", "shared-knowledge", "second-brain"],
    intelligenceSignals: [
      { id: "signal-1", title: "Research discovery density", source: "research", score: 86, status: "strong" },
      { id: "signal-2", title: "Shared knowledge asset depth", source: "shared-knowledge", score: 81, status: "strong" },
    ],
    insights: ["The mission now has reusable knowledge across all core layers."],
    patterns: ["Research repeatedly feeds creator, ministry, agency and intelligence outputs."],
    recommendations: ["Use the strongest cross-layer signals to prioritize next reuse opportunities."],
    dailyQuestions: ["What signal is strongest today?", "Where is the weakest knowledge link?"],
    weeklyReview: ["Review signal strength, reuse coverage and knowledge health."],
    relationshipView: [
      "Research",
      "Creator",
      "Ministry",
      "Executive",
      "Agency",
      "Shared Knowledge",
      "Second Brain",
    ],
    missionNavigator: [
      "Womanhood",
      "Research Assets",
      "Creator Assets",
      "Ministry Assets",
      "Executive Assets",
      "Agency Assets",
      "Knowledge Assets",
    ],
    crossWorkspaceSummary: ["All core Gamma workspaces now feed a single intelligence view."],
    workspaceStatus: [
      { workspace: "research", status: "active", progress: 62 },
      { workspace: "creator", status: "active", progress: 48 },
      { workspace: "ministry", status: "active", progress: 60 },
      { workspace: "executive", status: "active", progress: 51 },
      { workspace: "agency", status: "active", progress: 51 },
      { workspace: "shared-knowledge", status: "active", progress: 51 },
      { workspace: "second-brain", status: "active", progress: 48 },
      { workspace: "mission-registry", status: "active", progress: 100 },
    ],
    timeline: [
      { date: "2026-07-02", event: "Mission Created", status: "completed" },
      { date: "2026-07-02", event: "Research Started", status: "completed" },
      { date: "2026-07-03", event: "Research Completed", status: "completed" },
      { date: "2026-07-03", event: "Content Created", status: "completed" },
      { date: "2026-07-04", event: "Teaching Generated", status: "completed" },
      { date: "2026-07-05", event: "Assets Produced", status: "completed" },
      { date: "2026-07-06", event: "Knowledge Preserved", status: "planned" },
    ],
    relatedMissions: [{ id: "womanhood", title: "Research Mission 001 — Womanhood", status: "active" }],
    signalPreview: [
      "Research discoveries are consistently feeding downstream workspaces.",
      "Shared knowledge and second brain layers show strong reuse coverage.",
      "Executive priorities align with the current mission trajectory.",
    ],
    knowledgeGraphPreview: {
      nodes: [
        { id: "mission-womanhood", label: "Mission Womanhood", type: "mission" },
        { id: "layer-research", label: "Research Workspace", type: "workspace" },
        { id: "layer-shared", label: "Shared Knowledge", type: "workspace" },
        { id: "layer-brain", label: "Second Brain", type: "workspace" },
        { id: "layer-intelligence", label: "Knowledge Intelligence", type: "layer" },
      ],
      edges: [
        { from: "mission-womanhood", to: "layer-research", relation: "originates" },
        { from: "layer-research", to: "layer-intelligence", relation: "feeds" },
        { from: "layer-shared", to: "layer-intelligence", relation: "curates" },
        { from: "layer-brain", to: "layer-intelligence", relation: "synthesizes" },
      ],
    },
    readOnly: true,
    previewOnly: true,
    noAuth: true,
    noSessions: true,
    noJwt: true,
    noDatabase: true,
    noExecution: true,
    noPublishing: true,
    noOpenAI: true,
    noGraphWrites: true,
    noSocialPosting: true,
  }
}
