import type { MinistryWorkspace } from "./types"

export function getMockMinistryWorkspace(): MinistryWorkspace {
  return {
    id: "womanhood",
    name: "Ministry Workspace",
    relatedResearchMission: "Research Mission 001 — Womanhood",
    progress: 55,
    confidence: "high",
    status: "active",
    suggestedNextTeaching: "Teach a 4-part Womanhood Foundations series",
    teachingCount: 12,
    scriptureCount: 24,
    lessonCount: 10,
    themes: ["Identity", "Compassion", "Nurture", "Wisdom"],
    insights: ["Attachment language mirrors covenant faithfulness"],
    crossReferences: ["Isaiah 49:15", "Genesis 2:18-25"],
    timeline: [
      { date: "2026-07-02", event: "Mission defined", status: "completed" },
      { date: "2026-07-03", event: "Teaching themes mapped", status: "in-progress" },
      { date: "2026-07-04", event: "Series planning", status: "planned" },
    ],
    sermonSeries: ["Womanhood Foundations"],
    bibleStudies: ["Genesis and Identity"],
    teachingCourses: ["Biblical Womanhood Essentials"],
    smallGroupResources: ["Discussion prompts"],
    scriptureCollections: ["Isaiah 49:15"],
    prayerThemes: ["Compassion"],
    pastoralApplications: ["Mentorship pathways"],
    illustrations: ["Mother-child attachment as covenant illustration"],
    kingdomPrinciples: ["Dignity", "Stewardship", "Faithfulness"],
    readOnly: true,
    previewOnly: true,
    noAuth: true,
    noSessions: true,
    noJwt: true,
    noDatabase: true,
    noExecution: true,
    noPublishing: true,
    noOpenAI: true,
    noGraphWrites: true,
    noSocialPosting: true,
  }
}
