/**
 * Echo OAuth Adapter
 *
 * Implements OAuthAdapter from the Gamma Connector Platform SDK.
 * Generated by connector:scaffold — fill in service-specific values.
 */

import type { OAuthAdapter, TokenSet, TokenValidationResult } from '../../platform/connector-platform-sdk';

export const EchoOAuth: OAuthAdapter = {
  authorizationUrl: 'https://accounts.echo.com/oauth2/authorize',
  tokenUrl: 'https://accounts.echo.com/oauth2/token',
  requiredScopes: [
    // TODO: Add required scopes for Echo Service
    'echo.readonly',
  ],
  highRiskScopes: [
    // TODO: Add high-risk scopes (write, delete, send)
  ],

  async exchangeCode(code: string): Promise<TokenSet> {
    // TODO: Implement OAuth code exchange for Echo Service
    throw new Error('Not implemented: EchoOAuth.exchangeCode');
  },

  async refreshToken(refreshToken: string): Promise<TokenSet> {
    // TODO: Implement token refresh for Echo Service
    throw new Error('Not implemented: EchoOAuth.refreshToken');
  },

  validateToken(token: TokenSet): TokenValidationResult {
    const now = new Date();
    const expiresAt = new Date(token.expiresAt);
    const minutesUntilExpiry = Math.floor((expiresAt.getTime() - now.getTime()) / 60000);

    if (minutesUntilExpiry <= 0) {
      return { valid: false, issue: 'expired', maskedToken: maskToken(token.accessToken) };
    }
    if (minutesUntilExpiry < 10) {
      return { valid: true, issue: 'expiring_soon', minutesUntilExpiry, maskedToken: maskToken(token.accessToken) };
    }
    return { valid: true, minutesUntilExpiry, maskedToken: maskToken(token.accessToken) };
  },
};

function maskToken(token: string): string {
  if (!token || token.length < 8) return '****';
  return `oauth2_****${token.slice(-4)}`;
}
