/**
 * Echo Resource Parser
 *
 * Implements ResourceParser from the Gamma Connector Platform SDK.
 * Generated by connector:scaffold — fill in service-specific parsing logic.
 */

import type { ResourceParser, ValidationResult } from '../../platform/connector-platform-sdk';

// TODO: Define your resource type
export interface EchoResource {
  id: string;
  name: string;
  createdAt: Date;
  // Add fields specific to Echo Service
}

export const EchoParser: ResourceParser<unknown, EchoResource> = {
  parse(raw: unknown): EchoResource {
    const r = raw as Record<string, unknown>;
    // TODO: Map Echo Service API response to EchoResource
    return {
      id: String(r['id'] ?? ''),
      name: String(r['name'] ?? ''),
      createdAt: new Date(String(r['created_at'] ?? new Date().toISOString())),
    };
  },

  validate(resource: EchoResource): ValidationResult {
    const errors: string[] = [];
    if (!resource.id) errors.push('id is required');
    if (!resource.name) errors.push('name is required');
    return { valid: errors.length === 0, errors, warnings: [] };
  },

  sanitize(resource: EchoResource): EchoResource {
    // TODO: Redact any sensitive fields using the shared sanitizer
    return resource;
  },
};
