import type { AgencyWorkspace } from "./types"

export function getMockAgencyWorkspace(): AgencyWorkspace {
  return {
    id: "womanhood",
    name: "Agency Workspace",
    relatedMission: "Research Mission 001 — Womanhood",
    progress: 52,
    confidence: "high",
    pipelineStage: "proposal",
    projectStatus: "active",
    valueProposition: "Faith-informed strategy and content systems for mission-driven leaders.",
    revenuePotential: "Medium",
    nextSuggestedService: "Launch a womanhood strategy workshop package",
    proposalCount: 3,
    offerCount: 3,
    workshopCount: 2,
    packageCount: 3,
    timelineCount: 4,
    clientProposals: ["Foundations proposal"],
    servicePackages: ["Workshop package"],
    discoveryDocuments: ["Mission brief"],
    workshopPlans: ["4-week workshop"],
    consultingDeliverables: ["Executive recommendations"],
    presentationOutlines: ["Client narrative deck"],
    caseStudies: ["Mission-to-service transformation"],
    offerTemplates: ["Starter offer template"],
    roadmaps: ["90-day roadmap"],
    crossReferences: ["Isaiah 49:15"],
    timeline: [
      { date: "2026-07-02", event: "Mission discovery complete", status: "completed" },
      { date: "2026-07-03", event: "Offer architecture drafted", status: "in-progress" },
      { date: "2026-07-04", event: "Proposal packet outlined", status: "planned" },
      { date: "2026-07-05", event: "Agency preview generated", status: "planned" },
    ],
    relatedMissions: [{ id: "womanhood", title: "Research Mission 001 — Womanhood", status: "active" }],
    readOnly: true,
    previewOnly: true,
    noAuth: true,
    noSessions: true,
    noJwt: true,
    noDatabase: true,
    noExecution: true,
    noPublishing: true,
    noOpenAI: true,
    noGraphWrites: true,
    noSocialPosting: true,
  }
}
