import type { SharedKnowledgeWorkspace } from "./types"

export function getMockSharedKnowledgeWorkspace(): SharedKnowledgeWorkspace {
  return {
    id: "womanhood",
    name: "Shared Knowledge Layer",
    missionTitle: "Research Mission 001 — Womanhood",
    status: "active",
    confidence: "high",
    knowledgeHealthScore: 84,
    assetCount: 18,
    frameworkCount: 3,
    promptCount: 4,
    templateCount: 3,
    discoveryCount: 5,
    crossReferenceCount: 8,
    domainCount: 4,
    timelineCount: 5,
    knowledgeDomains: ["theology", "science", "culture", "leadership"],
    knowledgeCategories: [
      "discoveries",
      "principles",
      "frameworks",
      "prompts",
      "templates",
      "scripts",
      "teaching-models",
    ],
    knowledgeAssets: [
      {
        id: "asset-1",
        title: "Maternal Attachment Discovery",
        category: "discovery",
        domain: "science",
        confidence: "high",
        status: "curated",
        tags: ["womanhood", "bonding"],
        crossReferences: ["Isaiah 49:15"],
        relatedMissions: ["womanhood"],
        suggestedApplications: ["Teaching outline"],
      },
    ],
    discoveries: ["Oxytocin supports maternal bonding"],
    principles: ["Compassion reflects covenant faithfulness"],
    frameworks: ["Mission to Ministry Framework"],
    prompts: ["How does Scripture shape identity?"],
    templates: ["Offer Template: Advisory Retainer"],
    scripts: ["Session Script: Womanhood Foundations"],
    teachingModels: ["Teaching Model: Scripture to Practice"],
    bookStructures: ["Book Structure: Foundations of Womanhood"],
    courseStructures: ["Course Structure: Women Across Life Stages"],
    serviceModels: ["Service Model: Workshop and Advisory"],
    reusableComponents: ["Reusable Component: Cross-reference index"],
    crossReferences: ["Isaiah 49:15", "Genesis 2:18-25"],
    tags: ["womanhood", "identity", "discipleship"],
    timeline: [
      { date: "2026-07-02", event: "Research mission established", status: "completed" },
      { date: "2026-07-03", event: "Creator outputs mapped", status: "completed" },
      { date: "2026-07-04", event: "Ministry principles curated", status: "in-progress" },
      { date: "2026-07-05", event: "Agency frameworks promoted", status: "in-progress" },
      { date: "2026-07-05", event: "Shared knowledge preview published", status: "planned" },
    ],
    relatedMissions: [{ id: "womanhood", title: "Research Mission 001 — Womanhood", status: "active" }],
    suggestedApplications: [
      "Build a scripture-backed workshop path",
      "Create reusable client framework package",
      "Translate discoveries into editorial prompts",
    ],
    searchPreview: [
      "Discovery: Oxytocin supports maternal bonding",
      "Framework: Mission to Ministry Framework",
      "Template: Offer Template: Advisory Retainer",
    ],
    knowledgeGraphPreview: {
      nodes: [
        { id: "domain-theology", label: "Theology", type: "domain" },
        { id: "asset-discovery-1", label: "Maternal Attachment Discovery", type: "asset" },
        { id: "mission-womanhood", label: "Mission Womanhood", type: "mission" },
      ],
      edges: [
        { from: "domain-theology", to: "asset-discovery-1", relation: "contains" },
        { from: "mission-womanhood", to: "asset-discovery-1", relation: "contributes" },
      ],
    },
    readOnly: true,
    previewOnly: true,
    noAuth: true,
    noSessions: true,
    noJwt: true,
    noDatabase: true,
    noExecution: true,
    noPublishing: true,
    noOpenAI: true,
    noGraphWrites: true,
    noSocialPosting: true,
  }
}
