import type { SecondBrainWorkspace } from "./types"

export function getMockSecondBrainWorkspace(): SecondBrainWorkspace {
  return {
    id: "womanhood",
    name: "Second Brain Hub",
    currentMission: "Research Mission 001 — Womanhood",
    missionCount: 1,
    workspaceCount: 7,
    discoveryCount: 12,
    assetCount: 30,
    timelineCount: 6,
    priorityCount: 4,
    actionCount: 6,
    healthScore: 62,
    brainScore: 58,
    crossReferenceCount: 28,
    confidence: "high",
    researchProgress: 51,
    creatorProgress: 48,
    ministryProgress: 60,
    executivePriorities: ["Refine ministry lesson flow"],
    agencyPipeline: "proposal",
    knowledgeAssets: ["Framework: Research to Reusable Knowledge"],
    suggestedActions: ["Promote two discoveries into templates"],
    recentDiscoveries: ["Oxytocin appears central to maternal bonding"],
    stalledMissions: [],
    dailyReview: ["Check current mission progress"],
    weeklyReview: ["Review cross-workspace timeline"],
    dailyPrompts: [
      "What should I work on today?",
      "What have I learned?",
      "What can I create?",
      "What can I teach?",
      "What can I package?",
      "What can I reuse?",
    ],
    crossWorkspaceSummary: ["Research is feeding creator and ministry outputs"],
    growthIndicators: [
      { date: "2026-07-03", discoveries: 6, assets: 12, score: 47 },
      { date: "2026-07-04", discoveries: 9, assets: 20, score: 53 },
      { date: "2026-07-05", discoveries: 12, assets: 30, score: 58 },
    ],
    timeline: [
      { date: "2026-07-02", event: "Research workspace initiated", status: "completed" },
      { date: "2026-07-03", event: "Creator and ministry workspaces connected", status: "completed" },
      { date: "2026-07-04", event: "Executive and agency workspaces synchronized", status: "in-progress" },
      { date: "2026-07-05", event: "Shared knowledge layer integrated", status: "completed" },
      { date: "2026-07-05", event: "Second brain dashboard generated", status: "planned" },
      { date: "2026-07-05", event: "Weekly review snapshot prepared", status: "planned" },
    ],
    workspaceStatus: [
      { workspace: "research", status: "active", progress: 51 },
      { workspace: "creator", status: "active", progress: 48 },
      { workspace: "ministry", status: "active", progress: 60 },
      { workspace: "executive", status: "active", progress: 51 },
      { workspace: "agency", status: "active", progress: 51 },
      { workspace: "shared-knowledge", status: "active", progress: 51 },
      { workspace: "mission-registry", status: "active", progress: 100 },
    ],
    relatedMissions: [{ id: "womanhood", title: "Research Mission 001 — Womanhood", status: "active" }],
    readOnly: true,
    previewOnly: true,
    noAuth: true,
    noSessions: true,
    noJwt: true,
    noDatabase: true,
    noExecution: true,
    noPublishing: true,
    noOpenAI: true,
    noGraphWrites: true,
    noSocialPosting: true,
  }
}
