import type { AIMarketplaceWorkspace } from "./types"

export const AI_MARKETPLACE_ASSETS: AIMarketplaceWorkspace = {
  agents: [
    {
      id: "agent-research",
      name: "Research Agent",
      role: "research",
      version: "2.3.0",
      status: "deployed",
      description: "Deep research, literature synthesis, and evidence mapping",
      deploymentsCount: 342,
    },
    {
      id: "agent-ministry",
      name: "Ministry Agent",
      role: "ministry",
      version: "1.9.1",
      status: "deployed",
      description: "Sermon preparation, discipleship planning, and congregant care",
      deploymentsCount: 218,
    },
    {
      id: "agent-ceo",
      name: "CEO Agent",
      role: "ceo",
      version: "3.1.0",
      status: "deployed",
      description: "Executive intelligence, board reporting, and strategic decisions",
      deploymentsCount: 95,
    },
    {
      id: "agent-planner",
      name: "Planner Agent",
      role: "planner",
      version: "2.0.4",
      status: "deployed",
      description: "Mission planning, milestone tracking, and resource allocation",
      deploymentsCount: 476,
    },
    {
      id: "agent-writer",
      name: "Writer Agent",
      role: "writer",
      version: "2.8.0",
      status: "deployed",
      description: "Long-form content, editorial review, and publishing pipeline",
      deploymentsCount: 890,
    },
    {
      id: "agent-marketing",
      name: "Marketing Agent",
      role: "marketing",
      version: "1.7.2",
      status: "available",
      description: "Campaign strategy, audience analytics, and growth optimization",
      deploymentsCount: 164,
    },
    {
      id: "agent-strategy",
      name: "Strategy Agent",
      role: "strategy",
      version: "2.2.0",
      status: "available",
      description: "Competitive analysis, scenario planning, and strategic roadmaps",
      deploymentsCount: 127,
    },
  ],
  metrics: {
    totalAgents: 7,
    deployedAgents: 5,
    totalDeployments: 2312,
    healthScore: 91,
  },
}
