type LLMProvider =
  | "openai"
  | "gemini"
  | "claude"

type GenerateInput = {
  provider: LLMProvider
  prompt: string
  systemPrompt?: string
}

export async function llmGateway(
  input: GenerateInput
) {
  const {
    provider,
    prompt,
    systemPrompt,
  } = input

  /*
    FUTURE:
    Real API integrations here
  */

  if (provider === "openai") {
    return {
      provider,
      output: `
[OPENAI OUTPUT]

System:
${systemPrompt || "None"}

Prompt:
${prompt}

Generated by OpenAI simulation.
`,
    }
  }

  if (provider === "gemini") {
    return {
      provider,
      output: `
[GEMINI OUTPUT]

Prompt:
${prompt}

Generated by Gemini simulation.
`,
    }
  }

  if (provider === "claude") {
    return {
      provider,
      output: `
[CLAUDE OUTPUT]

Prompt:
${prompt}

Generated by Claude simulation.
`,
    }
  }

  return {
    provider,
    output: "No provider matched.",
  }
}