/**
 * Echo Connector Tests
 *
 * Generated by connector:scaffold.
 * All tests are deterministic — no Date.now(), no Math.random().
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { EchoOAuth } from '../../lib/connectors/echo/oauth-adapter';
import { EchoClient } from '../../lib/connectors/echo/api-client';
import { EchoParser } from '../../lib/connectors/echo/resource-parser';
import { EchoActions } from '../../lib/connectors/echo/action-set';
import { EchoReader } from '../../lib/gamma/echo-reader';
import { PLATFORM_BASE_TIME } from '../../lib/platform/mock-time-helpers';

const BASE_TIME = PLATFORM_BASE_TIME;

describe('Echo Connector', () => {

  describe('OAuth Adapter', () => {
    it('should have required scopes defined', () => {
      expect(EchoOAuth.requiredScopes.length).toBeGreaterThan(0);
    });

    it('should have authorization URL', () => {
      expect(EchoOAuth.authorizationUrl).toContain('http');
    });

    it('should mask token correctly', () => {
      const now = new Date();
      const token = {
        accessToken: 'test_access_token_1234',
        expiresAt: new Date(now.getTime() + 3600000),
        scopes: EchoOAuth.requiredScopes,
      };
      const result = EchoOAuth.validateToken(token);
      expect(result.maskedToken).toContain('****');
      expect(result.maskedToken).not.toContain('test_access_token');
    });

    it('should detect expired tokens', () => {
      const now = new Date();
      const expiredToken = {
        accessToken: 'expired_token_1234',
        expiresAt: new Date(now.getTime() - 1000),
        scopes: [],
      };
      const result = EchoOAuth.validateToken(expiredToken);
      expect(result.valid).toBe(false);
      expect(result.issue).toBe('expired');
    });

    it('should detect expiring-soon tokens', () => {
      const now = new Date();
      const expiringToken = {
        accessToken: 'expiring_token_1234',
        expiresAt: new Date(now.getTime() + 5 * 60 * 1000), // 5 min
        scopes: [],
      };
      const result = EchoOAuth.validateToken(expiringToken);
      expect(result.issue).toBe('expiring_soon');
    });
  });

  describe('API Client', () => {
    it('should have service name', () => {
      expect(EchoClient.serviceName).toBeTruthy();
    });

    it('should have base URL', () => {
      expect(EchoClient.baseUrl).toContain('http');
    });

    it('should have rate limit tiers', () => {
      expect(EchoClient.rateLimitTiers.length).toBeGreaterThan(0);
    });

    it('should have quota definitions', () => {
      expect(EchoClient.quotaDefinitions.length).toBeGreaterThan(0);
    });
  });

  describe('Resource Parser', () => {
    const rawResource = {
      id: 'resource_001',
      name: 'Test Resource',
      created_at: BASE_TIME.toISOString(),
    };

    it('should parse raw resource', () => {
      const parsed = EchoParser.parse(rawResource);
      expect(parsed.id).toBe('resource_001');
      expect(parsed.name).toBe('Test Resource');
    });

    it('should validate valid resource', () => {
      const parsed = EchoParser.parse(rawResource);
      const result = EchoParser.validate(parsed);
      expect(result.valid).toBe(true);
      expect(result.errors).toHaveLength(0);
    });

    it('should reject invalid resource (missing id)', () => {
      const invalid = EchoParser.parse({ name: 'No ID' });
      const result = EchoParser.validate(invalid);
      expect(result.valid).toBe(false);
    });

    it('should sanitize resource without error', () => {
      const parsed = EchoParser.parse(rawResource);
      expect(() => EchoParser.sanitize(parsed)).not.toThrow();
    });
  });

  describe('Action Set', () => {
    it('should have supported actions', () => {
      expect(EchoActions.supportedActions.length).toBeGreaterThan(0);
    });

    it('should preview action (zero side effects)', async () => {
      const request = {
        actionId: 'echo_read',
        params: {},
        requestedBy: 'test-user',
        requestedAt: BASE_TIME,
      };
      const preview = await EchoActions.preview(request);
      expect(preview.actionId).toBe('echo_read');
      expect(preview).toBeDefined();
    });

    it('should not execute without ENABLE_REAL_EXECUTION', async () => {
      const approved = {
        actionId: 'echo_create',
        params: {},
        requestedBy: 'user',
        requestedAt: BASE_TIME,
        approvedBy: 'admin',
        approvedAt: BASE_TIME,
        approvalReason: 'Test',
        queueId: 'queue_001',
      };
      const receipt = await EchoActions.execute(approved);
      // With ENABLE_REAL_EXECUTION=false, should queue not execute
      expect(receipt.status).toBe('queued');
    });
  });

  describe('Echo Reader (GAMMA Pattern)', () => {
    let reader: EchoReader;

    beforeEach(() => {
      reader = new EchoReader();
    });

    it('should start empty', () => {
      expect(reader.count()).toBe(0);
    });

    it('should store and retrieve resource', () => {
      const resource = {
        id: 'res_001',
        name: 'Test',
        createdAt: BASE_TIME,
      };
      reader.set('res_001', resource);
      const retrieved = reader.get('res_001');
      expect(retrieved?.id).toBe('res_001');
    });

    it('should get all resources', () => {
      reader.set('r1', { id: 'r1', name: 'A', createdAt: BASE_TIME });
      reader.set('r2', { id: 'r2', name: 'B', createdAt: BASE_TIME });
      expect(reader.all()).toHaveLength(2);
    });

    it('should filter resources', () => {
      reader.set('r1', { id: 'r1', name: 'Alpha', createdAt: BASE_TIME });
      reader.set('r2', { id: 'r2', name: 'Beta', createdAt: BASE_TIME });
      const found = reader.filter(r => r.name.startsWith('A'));
      expect(found).toHaveLength(1);
      expect(found[0].name).toBe('Alpha');
    });

    it('should get summary deterministically', () => {
      reader.set('r1', { id: 'r1', name: 'A', createdAt: BASE_TIME });
      const summary1 = reader.getSummary(BASE_TIME);
      const summary2 = reader.getSummary(BASE_TIME);
      expect(summary1).toEqual(summary2);
    });

    it('should not use Date.now() internally', () => {
      // Calling all time-based methods with explicit time
      const summary = reader.getSummary(BASE_TIME);
      const recent = reader.getRecent(BASE_TIME);
      expect(summary).toBeDefined();
      expect(recent).toBeDefined();
    });
  });
});
