import type { InferenceWorkspace } from "./types"

export function getMockInferenceWorkspace(): InferenceWorkspace {
  return {
    mission: "womanhood",
    missionTitle: "Research Mission 001 - Womanhood",
    inferenceCount: 8,
    gapCount: 5,
    unansweredQuestions: 4,
    unusedDiscoveries: 3,
    missingFrameworkCount: 1,
    coverageScore: 76,
    maturityScore: 61,
    confidenceScore: 73,
    recommendationScore: 77,
    healthScore: 72,
    discoveries: 12,
    questions: 8,
    answeredQuestions: 4,
    frameworks: 4,
    missingFrameworks: ["taxonomy.md"],
    creatorAssets: 4,
    teachings: 4,
    executivePriorities: 5,
    recommendationCount: 6,
    missionAreasNeedingAttention: ["creator", "executive"],
    workspaceWeaknesses: [
      { workspace: "creator", score: 48, status: "weak" },
      { workspace: "executive", score: 51, status: "watch" },
    ],
    knowledgeGaps: [
      {
        id: "gap-1",
        title: "Hormone explanation depth",
        description: "Emotional fluctuation questions remain partially answered.",
        severity: "high",
      },
    ],
    knowledgeOpportunities: [
      {
        id: "opportunity-1",
        category: "knowledge-opportunity",
        sourceType: "discovery",
        source: "Oxytocin increases bonding",
        inference: "Potential creator asset is missing.",
        suggestedOutput: "article",
        suggestedAction: "Create a motherhood article based on bonding discovery.",
        confidence: "high",
        priority: "high",
      },
    ],
    unusedResearch: [
      {
        id: "unused-1",
        category: "unused-research",
        sourceType: "discovery",
        source: "Women contribute significantly to society",
        inference: "Executive workshop opportunity is underused.",
        suggestedOutput: "seminar.md",
        suggestedAction: "Convert discovery into agency seminar outline.",
        confidence: "moderate",
        priority: "medium",
      },
    ],
    missingAssets: [
      {
        id: "missing-1",
        category: "missing-asset",
        sourceType: "framework",
        source: "taxonomy.md",
        inference: "Core framework missing from operational set.",
        suggestedOutput: "taxonomy.md",
        suggestedAction: "Build taxonomy structure for womanhood knowledge graph terms.",
        confidence: "high",
        priority: "high",
      },
    ],
    suggestedActions: [
      "Expand hormones.md with unanswered emotional fluctuation pathways.",
      "Create motherhood creator article from bonding discovery.",
      "Convert social contribution discovery into seminar.md.",
    ],
    timeline: [
      { date: "2026-07-04", event: "Inference baseline generated", status: "completed" },
      { date: "2026-07-05", event: "Gap mapping expanded", status: "completed" },
      { date: "2026-07-06", event: "Reason-over-knowledge preview", status: "planned" },
    ],
    readOnly: true,
    previewOnly: true,
    noAuth: true,
    noSessions: true,
    noJwt: true,
    noDatabase: true,
    noExecution: true,
    noPublishing: true,
    noOpenAI: true,
    noGraphWrites: true,
    noSocialPosting: true,
  }
}
