export type GammaStage5SurfaceMethod = "GET";
export type GammaStage5SurfaceAudience = "operator" | "monitor" | "release-client";
export type GammaStage5ArtifactCategory =
  | "readiness"
  | "evidence"
  | "release-control"
  | "adapter"
  | "operator"
  | "release-artifact"
  | "cutover";
export type GammaStage5GovernanceClassification =
  | "operator-review"
  | "monitoring"
  | "release-client"
  | "human-approval-required";
export type GammaStage5ReleaseStatus =
  | "ready"
  | "pending-operator"
  | "pending-human-approval"
  | "audit-ready";
export type GammaStage5DeprecationStatus = "active" | "deprecated";

export interface GammaStage5Surface {
  order: number;
  path: string;
  method: GammaStage5SurfaceMethod;
  audience: GammaStage5SurfaceAudience;
  sourceContract: string;
  smoke: true;
  manifest: true;
  sdk: true;
  openapi: true;
  dashboard: true;
  artifactCategory: GammaStage5ArtifactCategory;
  governanceClassification: GammaStage5GovernanceClassification;
  releaseStatus: GammaStage5ReleaseStatus;
  deprecationStatus: GammaStage5DeprecationStatus;
}

export interface GammaStage5SmokeRoute {
  group: "public" | "gamma" | "executive" | "admin";
  path: string;
}

const active = "active" as const;

export const GAMMA_STAGE_5_SURFACES = [
  {
    order: 1,
    path: "/api/gamma/stage-5/readiness",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-readiness.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "readiness",
    governanceClassification: "operator-review",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 2,
    path: "/api/gamma/stage-5/evidence",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-evidence.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "evidence",
    governanceClassification: "operator-review",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 3,
    path: "/api/gamma/stage-5/release-gate",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-release-gate.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-control",
    governanceClassification: "human-approval-required",
    releaseStatus: "pending-human-approval",
    deprecationStatus: active,
  },
  {
    order: 4,
    path: "/api/gamma/stage-5/promotion-checklist",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-promotion-checklist.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-control",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 5,
    path: "/api/gamma/stage-5/deployment-summary",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-deployment-summary.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-artifact",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 6,
    path: "/api/gamma/stage-5/operator-brief",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-operator-brief.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "operator",
    governanceClassification: "operator-review",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 7,
    path: "/api/gamma/stage-5/health",
    method: "GET",
    audience: "monitor",
    sourceContract: "src/lib/gamma-2/stage-5-health.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "readiness",
    governanceClassification: "monitoring",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 8,
    path: "/api/gamma/stage-5/release-dashboard",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-release-dashboard.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "adapter",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 9,
    path: "/api/gamma/stage-5/api-manifest",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-api-manifest.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "adapter",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 10,
    path: "/api/gamma/stage-5/openapi",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-openapi.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "adapter",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 11,
    path: "/api/gamma/stage-5/sdk",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-sdk.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "adapter",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 12,
    path: "/api/gamma/stage-5/contract-digest",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-contract-digest.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "adapter",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 13,
    path: "/api/gamma/stage-5/release-attestation",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-release-attestation.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-artifact",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 14,
    path: "/api/gamma/stage-5/rollback-plan",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-rollback-plan.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-control",
    governanceClassification: "operator-review",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 15,
    path: "/api/gamma/stage-5/operator-handoff",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-operator-handoff.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "operator",
    governanceClassification: "operator-review",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 16,
    path: "/api/gamma/stage-5/audit-ledger",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-audit-ledger.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "evidence",
    governanceClassification: "operator-review",
    releaseStatus: "audit-ready",
    deprecationStatus: active,
  },
  {
    order: 17,
    path: "/api/gamma/stage-5/deployment-receipt",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-deployment-receipt.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-artifact",
    governanceClassification: "operator-review",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 18,
    path: "/api/gamma/stage-5/promotion-journal",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-promotion-journal.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-artifact",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 19,
    path: "/api/gamma/stage-5/operator-signoff",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-operator-signoff.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "operator",
    governanceClassification: "human-approval-required",
    releaseStatus: "pending-human-approval",
    deprecationStatus: active,
  },
  {
    order: 20,
    path: "/api/gamma/stage-5/evidence-index",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-evidence-index.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "evidence",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 21,
    path: "/api/gamma/stage-5/release-bundle",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-release-bundle.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-artifact",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 22,
    path: "/api/gamma/stage-5/release-archive-manifest",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-release-archive-manifest.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-artifact",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 23,
    path: "/api/gamma/stage-5/release-retention-policy",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-release-retention-policy.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-artifact",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 24,
    path: "/api/gamma/stage-5/release-compliance-matrix",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-release-compliance-matrix.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "evidence",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 25,
    path: "/api/gamma/stage-5/release-exception-register",
    method: "GET",
    audience: "release-client",
    sourceContract: "src/lib/gamma-2/stage-5-release-exception-register.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "evidence",
    governanceClassification: "release-client",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 26,
    path: "/api/gamma/stage-5/release-governance-map",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-governance-map.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "evidence",
    governanceClassification: "operator-review",
    releaseStatus: "ready",
    deprecationStatus: active,
  },
  {
    order: 27,
    path: "/api/gamma/stage-5/release-decision-record",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-decision-record.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-control",
    governanceClassification: "human-approval-required",
    releaseStatus: "pending-human-approval",
    deprecationStatus: active,
  },
  {
    order: 28,
    path: "/api/gamma/stage-5/release-approval-packet",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-approval-packet.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-control",
    governanceClassification: "human-approval-required",
    releaseStatus: "pending-human-approval",
    deprecationStatus: active,
  },
  {
    order: 29,
    path: "/api/gamma/stage-5/release-promotion-plan",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-promotion-plan.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-control",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 30,
    path: "/api/gamma/stage-5/release-cutover-checklist",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-cutover-checklist.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "cutover",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 31,
    path: "/api/gamma/stage-5/release-traffic-shift-plan",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-traffic-shift-plan.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "cutover",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 32,
    path: "/api/gamma/stage-5/release-monitoring-plan",
    method: "GET",
    audience: "monitor",
    sourceContract: "src/lib/gamma-2/stage-5-release-monitoring-plan.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "cutover",
    governanceClassification: "monitoring",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 33,
    path: "/api/gamma/stage-5/release-post-promotion-review",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-post-promotion-review.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "cutover",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 34,
    path: "/api/gamma/stage-5/release-operations-index",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-operations-index.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "operator",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 35,
    path: "/api/gamma/stage-5/release-closeout-packet",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-closeout-packet.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-artifact",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 36,
    path: "/api/gamma/stage-5/release-closure-ledger",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-closure-ledger.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-artifact",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 37,
    path: "/api/gamma/stage-5/release-completion-certificate",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-completion-certificate.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-artifact",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 38,
    path: "/api/gamma/stage-5/release-finalization-index",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-finalization-index.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-artifact",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 39,
    path: "/api/gamma/stage-5/release-operator-registry",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-operator-registry.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "operator",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 40,
    path: "/api/gamma/stage-5/release-operator-action-queue",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-operator-action-queue.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "operator",
    governanceClassification: "operator-review",
    releaseStatus: "pending-operator",
    deprecationStatus: active,
  },
  {
    order: 41,
    path: "/api/gamma/stage-5/release-operator-approval-packet",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-operator-approval-packet.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "operator",
    governanceClassification: "human-approval-required",
    releaseStatus: "pending-human-approval",
    deprecationStatus: active,
  },
  {
    order: 42,
    path: "/api/gamma/stage-5/release-operator-approval-audit-trail",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-operator-approval-audit-trail.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "evidence",
    governanceClassification: "operator-review",
    releaseStatus: "audit-ready",
    deprecationStatus: active,
  },
  {
    order: 43,
    path: "/api/gamma/stage-5/release-operator-approval-receipt",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-operator-approval-receipt.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "operator",
    governanceClassification: "human-approval-required",
    releaseStatus: "pending-human-approval",
    deprecationStatus: active,
  },
  {
    order: 44,
    path: "/api/gamma/stage-5/release-production-authorization-ledger",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-production-authorization-ledger.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "release-control",
    governanceClassification: "human-approval-required",
    releaseStatus: "pending-human-approval",
    deprecationStatus: active,
  },
  {
    order: 45,
    path: "/api/gamma/stage-5/release-production-cutover-packet",
    method: "GET",
    audience: "operator",
    sourceContract: "src/lib/gamma-2/stage-5-release-production-cutover-packet.ts",
    smoke: true,
    manifest: true,
    sdk: true,
    openapi: true,
    dashboard: true,
    artifactCategory: "cutover",
    governanceClassification: "human-approval-required",
    releaseStatus: "pending-human-approval",
    deprecationStatus: active,
  },
] as const satisfies readonly GammaStage5Surface[];

export const GAMMA_STAGE_5_SUPPORTING_SMOKE_ROUTES = [
  { group: "public", path: "/api/health" },
  { group: "gamma", path: "/gamma-stage-5" },
  { group: "executive", path: "/api/executive/health" },
  { group: "executive", path: "/api/executive/runtime" },
  { group: "executive", path: "/api/executive/command-center" },
  { group: "executive", path: "/api/executive/boardroom" },
  { group: "executive", path: "/api/executive/forecast" },
  { group: "executive", path: "/api/executive/strategic-plan" },
  { group: "executive", path: "/api/executive/goals" },
  { group: "executive", path: "/api/executive/knowledge-graph" },
  { group: "executive", path: "/api/executive/simulations" },
  { group: "executive", path: "/api/executive/scenarios" },
  { group: "admin", path: "/admin/runtime" },
  { group: "admin", path: "/admin/command-center" },
  { group: "admin", path: "/admin/operations" },
  { group: "admin", path: "/admin/boardroom" },
  { group: "admin", path: "/admin/strategic-plan" },
  { group: "admin", path: "/admin/goals" },
  { group: "admin", path: "/admin/knowledge-graph" },
  { group: "admin", path: "/admin/simulations" },
  { group: "admin", path: "/admin/scenarios" },
  { group: "admin", path: "/admin/revenue" },
  { group: "admin", path: "/admin/delivery" },
] as const satisfies readonly GammaStage5SmokeRoute[];

function byOrder(a: GammaStage5Surface, b: GammaStage5Surface) {
  return a.order - b.order;
}

export function getGammaStage5Surfaces(): GammaStage5Surface[] {
  return [...GAMMA_STAGE_5_SURFACES].sort(byOrder);
}

export function getGammaStage5EndpointPaths(): string[] {
  return getGammaStage5Surfaces().map((surface) => surface.path);
}

export function getGammaStage5ManifestSurfaces(): GammaStage5Surface[] {
  return getGammaStage5Surfaces().filter((surface) => surface.manifest);
}

export function getGammaStage5SdkSurfaces(): GammaStage5Surface[] {
  return getGammaStage5Surfaces().filter((surface) => surface.sdk);
}

export function getGammaStage5OpenApiSurfaces(): GammaStage5Surface[] {
  return getGammaStage5Surfaces().filter((surface) => surface.openapi);
}

export function getGammaStage5DashboardSurfaces(): GammaStage5Surface[] {
  return getGammaStage5Surfaces().filter((surface) => surface.dashboard);
}

export function getGammaStage5ReleaseArtifactSurfaces(): GammaStage5Surface[] {
  return getGammaStage5Surfaces().filter(
    (surface) =>
      surface.artifactCategory === "release-artifact" ||
      surface.artifactCategory === "release-control" ||
      surface.artifactCategory === "cutover" ||
      surface.artifactCategory === "operator"
  );
}

export function getGammaStage5SmokeRoutes(): GammaStage5SmokeRoute[] {
  return [
    ...GAMMA_STAGE_5_SUPPORTING_SMOKE_ROUTES.slice(0, 2),
    ...getGammaStage5Surfaces()
      .filter((surface) => surface.smoke)
      .map((surface) => ({ group: "gamma" as const, path: surface.path })),
    ...GAMMA_STAGE_5_SUPPORTING_SMOKE_ROUTES.slice(2),
  ];
}

export const GAMMA_STAGE_5_SURFACE_COUNTS = {
  totalEndpoints: getGammaStage5Surfaces().length,
  totalSmokeCoveredRoutes: getGammaStage5SmokeRoutes().length,
  manifestCount: getGammaStage5ManifestSurfaces().length,
  sdkCount: getGammaStage5SdkSurfaces().length,
  openapiCount: getGammaStage5OpenApiSurfaces().length,
  dashboardCount: getGammaStage5DashboardSurfaces().length,
  releaseArtifactCount: getGammaStage5ReleaseArtifactSurfaces().length,
} as const;

export const GAMMA_STAGE_5_SMOKE_SUMMARY =
  `${GAMMA_STAGE_5_SURFACE_COUNTS.totalSmokeCoveredRoutes} routes passed, 0 failed` as const;
