#!/usr/bin/env node
/**
 * Gamma Connector Scaffold Generator
 * npm run connector:scaffold -- --name=calendar --service="Google Calendar" --baseUrl="https://www.googleapis.com/calendar/v3"
 *
 * Generates a complete connector from the platform SDK:
 *   lib/connectors/{name}/oauth-adapter.ts
 *   lib/connectors/{name}/api-client.ts
 *   lib/connectors/{name}/resource-parser.ts
 *   lib/connectors/{name}/action-set.ts
 *   lib/connectors/{name}/health-checker.ts
 *   lib/connectors/{name}/index.ts
 *   lib/gamma/{name}-reader.ts
 *   app/{name}-connector/page.tsx
 *   tests/connectors/{name}.test.ts
 *   docs/connectors/{name}.md
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT = process.cwd();

// ─── Parse CLI args ────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const argMap: Record<string, string> = {};
for (const arg of args) {
  const [key, value] = arg.replace(/^--/, '').split('=');
  argMap[key] = value;
}

const connectorName = argMap['name'];
const serviceName = argMap['service'] ?? `${connectorName} Service`;
const baseUrl = argMap['baseUrl'] ?? `https://api.${connectorName}.com/v1`;

if (!connectorName) {
  console.error('Usage: npm run connector:scaffold -- --name=<connector> --service="<Service Name>" --baseUrl=<url>');
  process.exit(1);
}

const CONNECTOR_DIR = path.join(ROOT, 'lib', 'connectors', connectorName);
const GAMMA_DIR = path.join(ROOT, 'lib', 'gamma');
const APP_DIR = path.join(ROOT, 'app', `${connectorName}-connector`);
const TEST_DIR = path.join(ROOT, 'tests', 'connectors');
const DOCS_DIR = path.join(ROOT, 'docs', 'connectors');

const Name = connectorName.charAt(0).toUpperCase() + connectorName.slice(1);

// ─── Templates ────────────────────────────────────────────────────────────────

const oauthAdapterTemplate = `/**
 * ${Name} OAuth Adapter
 *
 * Implements OAuthAdapter from the Gamma Connector Platform SDK.
 * Generated by connector:scaffold — fill in service-specific values.
 */

import type { OAuthAdapter, TokenSet, TokenValidationResult } from '../../platform/connector-platform-sdk';

export const ${Name}OAuth: OAuthAdapter = {
  authorizationUrl: 'https://accounts.${connectorName}.com/oauth2/authorize',
  tokenUrl: 'https://accounts.${connectorName}.com/oauth2/token',
  requiredScopes: [
    // TODO: Add required scopes for ${serviceName}
    '${connectorName}.readonly',
  ],
  highRiskScopes: [
    // TODO: Add high-risk scopes (write, delete, send)
  ],

  async exchangeCode(code: string): Promise<TokenSet> {
    // TODO: Implement OAuth code exchange for ${serviceName}
    throw new Error('Not implemented: ${Name}OAuth.exchangeCode');
  },

  async refreshToken(refreshToken: string): Promise<TokenSet> {
    // TODO: Implement token refresh for ${serviceName}
    throw new Error('Not implemented: ${Name}OAuth.refreshToken');
  },

  validateToken(token: TokenSet): TokenValidationResult {
    const now = new Date();
    const expiresAt = new Date(token.expiresAt);
    const minutesUntilExpiry = Math.floor((expiresAt.getTime() - now.getTime()) / 60000);

    if (minutesUntilExpiry <= 0) {
      return { valid: false, issue: 'expired', maskedToken: maskToken(token.accessToken) };
    }
    if (minutesUntilExpiry < 10) {
      return { valid: true, issue: 'expiring_soon', minutesUntilExpiry, maskedToken: maskToken(token.accessToken) };
    }
    return { valid: true, minutesUntilExpiry, maskedToken: maskToken(token.accessToken) };
  },
};

function maskToken(token: string): string {
  if (!token || token.length < 8) return '****';
  return \`oauth2_****\${token.slice(-4)}\`;
}
`;

const apiClientTemplate = `/**
 * ${Name} API Client
 *
 * Implements ApiClient from the Gamma Connector Platform SDK.
 * Generated by connector:scaffold — fill in service-specific API calls.
 */

import type { ApiClient, RateLimitTier, QuotaDefinition } from '../../platform/connector-platform-sdk';

export const ${Name}Client: ApiClient = {
  serviceName: '${serviceName}',
  baseUrl: '${baseUrl}',

  rateLimitTiers: [
    { name: 'Normal',   thresholdPercent: 70, score: 100, backoffSeconds: 0 },
    { name: 'Elevated', thresholdPercent: 85, score: 70,  backoffSeconds: 10 },
    { name: 'Warning',  thresholdPercent: 95, score: 40,  backoffSeconds: 30 },
    { name: 'Limited',  thresholdPercent: 100, score: 10, backoffSeconds: 60 },
  ] satisfies RateLimitTier[],

  quotaDefinitions: [
    // TODO: Add quota definitions for ${serviceName}
    { name: 'read',   limit: 1000, windowSeconds: 86400 },
    { name: 'write',  limit: 500,  windowSeconds: 86400 },
  ] satisfies QuotaDefinition[],

  async read(resource: string, params?: Record<string, string>): Promise<unknown> {
    // TODO: Implement GET ${baseUrl}/{resource}
    throw new Error(\`Not implemented: ${Name}Client.read(\${resource})\`);
  },

  async create(resource: string, payload: unknown): Promise<unknown> {
    // TODO: Implement POST ${baseUrl}/{resource}
    throw new Error(\`Not implemented: ${Name}Client.create(\${resource})\`);
  },

  async update(resource: string, id: string, payload: unknown): Promise<unknown> {
    // TODO: Implement PATCH ${baseUrl}/{resource}/{id}
    throw new Error(\`Not implemented: ${Name}Client.update(\${resource}, \${id})\`);
  },

  async delete(resource: string, id: string): Promise<void> {
    // TODO: Implement DELETE ${baseUrl}/{resource}/{id}
    throw new Error(\`Not implemented: ${Name}Client.delete(\${resource}, \${id})\`);
  },
};
`;

const resourceParserTemplate = `/**
 * ${Name} Resource Parser
 *
 * Implements ResourceParser from the Gamma Connector Platform SDK.
 * Generated by connector:scaffold — fill in service-specific parsing logic.
 */

import type { ResourceParser, ValidationResult } from '../../platform/connector-platform-sdk';

// TODO: Define your resource type
export interface ${Name}Resource {
  id: string;
  name: string;
  createdAt: Date;
  // Add fields specific to ${serviceName}
}

export const ${Name}Parser: ResourceParser<unknown, ${Name}Resource> = {
  parse(raw: unknown): ${Name}Resource {
    const r = raw as Record<string, unknown>;
    // TODO: Map ${serviceName} API response to ${Name}Resource
    return {
      id: String(r['id'] ?? ''),
      name: String(r['name'] ?? ''),
      createdAt: new Date(String(r['created_at'] ?? new Date().toISOString())),
    };
  },

  validate(resource: ${Name}Resource): ValidationResult {
    const errors: string[] = [];
    if (!resource.id) errors.push('id is required');
    if (!resource.name) errors.push('name is required');
    return { valid: errors.length === 0, errors, warnings: [] };
  },

  sanitize(resource: ${Name}Resource): ${Name}Resource {
    // TODO: Redact any sensitive fields using the shared sanitizer
    return resource;
  },
};
`;

const actionSetTemplate = `/**
 * ${Name} Action Set
 *
 * Implements ActionSet from the Gamma Connector Platform SDK.
 * Generated by connector:scaffold — define actions specific to ${serviceName}.
 *
 * SAFETY: All actions require ENABLE_REAL_EXECUTION=true AND approval.
 */

import type {
  ActionSet,
  ActionDefinition,
  ActionRequest,
  ActionPreview,
  ApprovedAction,
  ActionReceipt,
} from '../../platform/connector-platform-sdk';

export const ${Name}Actions: ActionSet = {
  supportedActions: [
    {
      id: '${connectorName}_read',
      name: 'Read ${Name} Resources',
      description: 'Read resources from ${serviceName}',
      riskLevel: 'low',
      requiresApproval: false,
      requiresFeatureFlag: false,
    },
    {
      id: '${connectorName}_create',
      name: 'Create ${Name} Resource',
      description: 'Create a new resource in ${serviceName}',
      riskLevel: 'medium',
      requiresApproval: true,
      requiresFeatureFlag: true,
      featureFlagKey: 'ENABLE_REAL_EXECUTION',
    },
    // TODO: Add more actions specific to ${serviceName}
  ] satisfies ActionDefinition[],

  async preview(action: ActionRequest): Promise<ActionPreview> {
    return {
      actionId: action.actionId,
      description: \`Would execute \${action.actionId} in ${serviceName}\`,
      affectedResources: [],
      estimatedImpact: 'None (preview only)',
      riskWarnings: [],
      requiresApproval: true,
    };
  },

  async execute(action: ApprovedAction): Promise<ActionReceipt> {
    const realExecution = process.env.ENABLE_REAL_EXECUTION === 'true';
    if (!realExecution) {
      return {
        actionId: action.actionId,
        queueId: action.queueId,
        status: 'queued',
        executedAt: action.approvedAt,
        auditId: \`audit_\${action.queueId}\`,
      };
    }
    // TODO: Implement real execution for ${serviceName}
    throw new Error('Real execution not yet implemented for ${Name}');
  },
};
`;

const readerTemplate = `/**
 * ${Name} Reader (GAMMA)
 *
 * Deterministic read-only queries for ${connectorName} data.
 * All time-dependent methods accept currentTime parameter.
 * Extends GammaReaderBase — no store/retrieve boilerplate needed.
 */

import { GammaReaderBase } from '../platform/gamma-reader-base';
import type { ${Name}Resource } from '../connectors/${connectorName}/resource-parser';

export class ${Name}Reader extends GammaReaderBase<${Name}Resource> {
  /**
   * Get by name (deterministic)
   */
  getByName(name: string, currentTime: Date): ${Name}Resource | undefined {
    return this.find(r => r.name === name);
  }

  /**
   * Get recent resources (deterministic — uses currentTime)
   */
  getRecent(currentTime: Date, limitDays = 7): ${Name}Resource[] {
    const cutoff = new Date(currentTime.getTime() - limitDays * 24 * 60 * 60 * 1000);
    return this.since(r => r.createdAt, cutoff);
  }

  /**
   * Get summary (deterministic)
   */
  getSummary(currentTime: Date): {
    total: number;
    recent: number;
    lastUpdated: Date | null;
  } {
    const all = this.all();
    const recent = this.getRecent(currentTime);
    const latest = this.latest(r => r.createdAt);
    return {
      total: all.length,
      recent: recent.length,
      lastUpdated: latest ? new Date(latest.createdAt) : null,
    };
  }
}
`;

const dashboardTemplate = `'use client';

import { useState, useEffect } from 'react';

interface ${Name}Summary {
  total: number;
  recent: number;
  status: string;
}

export default function ${Name}ConnectorDashboard() {
  const [summary, setSummary] = useState<${Name}Summary | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch('/api/connectors/${connectorName}/status');
        if (res.ok) setSummary(await res.json());
      } catch (e) {
        console.error('Failed to load ${connectorName} status', e);
      } finally {
        setLoading(false);
      }
    }
    load();
    const interval = setInterval(load, 30000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="min-h-screen bg-slate-50 p-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">${serviceName} Connector</h1>
        <p className="text-slate-600 mb-8">Gamma Platform — Phase XVI</p>

        {loading && (
          <div className="bg-white rounded-lg border border-slate-200 p-6">
            <p className="text-slate-600">Loading...</p>
          </div>
        )}

        {!loading && summary && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-white rounded-lg border border-slate-200 p-6">
              <div className="text-sm text-slate-600">Total Resources</div>
              <div className="text-3xl font-bold text-slate-900 mt-2">{summary.total}</div>
            </div>
            <div className="bg-white rounded-lg border border-slate-200 p-6">
              <div className="text-sm text-slate-600">Recent (7 days)</div>
              <div className="text-3xl font-bold text-slate-900 mt-2">{summary.recent}</div>
            </div>
            <div className="bg-white rounded-lg border border-slate-200 p-6">
              <div className="text-sm text-slate-600">Status</div>
              <div className="text-3xl font-bold text-slate-900 mt-2 capitalize">{summary.status}</div>
            </div>
          </div>
        )}

        {!loading && !summary && (
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6">
            <p className="text-yellow-800 font-semibold">Connector not yet configured</p>
            <p className="text-yellow-700 mt-1">
              Implement the ${Name} OAuth adapter, API client, and resource parser to activate.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
`;

const testTemplate = `/**
 * ${Name} Connector Tests
 *
 * Generated by connector:scaffold.
 * All tests are deterministic — no Date.now(), no Math.random().
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { ${Name}OAuth } from '../../lib/connectors/${connectorName}/oauth-adapter';
import { ${Name}Client } from '../../lib/connectors/${connectorName}/api-client';
import { ${Name}Parser } from '../../lib/connectors/${connectorName}/resource-parser';
import { ${Name}Actions } from '../../lib/connectors/${connectorName}/action-set';
import { ${Name}Reader } from '../../lib/gamma/${connectorName}-reader';
import { PLATFORM_BASE_TIME } from '../../lib/platform/mock-time-helpers';

const BASE_TIME = PLATFORM_BASE_TIME;

describe('${Name} Connector', () => {

  describe('OAuth Adapter', () => {
    it('should have required scopes defined', () => {
      expect(${Name}OAuth.requiredScopes.length).toBeGreaterThan(0);
    });

    it('should have authorization URL', () => {
      expect(${Name}OAuth.authorizationUrl).toContain('http');
    });

    it('should mask token correctly', () => {
      const token = {
        accessToken: 'test_access_token_1234',
        expiresAt: new Date(BASE_TIME.getTime() + 3600000),
        scopes: ${Name}OAuth.requiredScopes,
      };
      const result = ${Name}OAuth.validateToken(token);
      expect(result.maskedToken).toContain('****');
      expect(result.maskedToken).not.toContain('test_access_token');
    });

    it('should detect expired tokens', () => {
      const expiredToken = {
        accessToken: 'expired_token_1234',
        expiresAt: new Date(BASE_TIME.getTime() - 1000),
        scopes: [],
      };
      const result = ${Name}OAuth.validateToken(expiredToken);
      expect(result.valid).toBe(false);
      expect(result.issue).toBe('expired');
    });

    it('should detect expiring-soon tokens', () => {
      const expiringToken = {
        accessToken: 'expiring_token_1234',
        expiresAt: new Date(BASE_TIME.getTime() + 5 * 60 * 1000), // 5 min
        scopes: [],
      };
      const result = ${Name}OAuth.validateToken(expiringToken);
      expect(result.issue).toBe('expiring_soon');
    });
  });

  describe('API Client', () => {
    it('should have service name', () => {
      expect(${Name}Client.serviceName).toBeTruthy();
    });

    it('should have base URL', () => {
      expect(${Name}Client.baseUrl).toContain('http');
    });

    it('should have rate limit tiers', () => {
      expect(${Name}Client.rateLimitTiers.length).toBeGreaterThan(0);
    });

    it('should have quota definitions', () => {
      expect(${Name}Client.quotaDefinitions.length).toBeGreaterThan(0);
    });
  });

  describe('Resource Parser', () => {
    const rawResource = {
      id: 'resource_001',
      name: 'Test Resource',
      created_at: BASE_TIME.toISOString(),
    };

    it('should parse raw resource', () => {
      const parsed = ${Name}Parser.parse(rawResource);
      expect(parsed.id).toBe('resource_001');
      expect(parsed.name).toBe('Test Resource');
    });

    it('should validate valid resource', () => {
      const parsed = ${Name}Parser.parse(rawResource);
      const result = ${Name}Parser.validate(parsed);
      expect(result.valid).toBe(true);
      expect(result.errors).toHaveLength(0);
    });

    it('should reject invalid resource (missing id)', () => {
      const invalid = ${Name}Parser.parse({ name: 'No ID' });
      const result = ${Name}Parser.validate(invalid);
      expect(result.valid).toBe(false);
    });

    it('should sanitize resource without error', () => {
      const parsed = ${Name}Parser.parse(rawResource);
      expect(() => ${Name}Parser.sanitize(parsed)).not.toThrow();
    });
  });

  describe('Action Set', () => {
    it('should have supported actions', () => {
      expect(${Name}Actions.supportedActions.length).toBeGreaterThan(0);
    });

    it('should preview action (zero side effects)', async () => {
      const request = {
        actionId: '${connectorName}_read',
        params: {},
        requestedBy: 'test-user',
        requestedAt: BASE_TIME,
      };
      const preview = await ${Name}Actions.preview(request);
      expect(preview.actionId).toBe('${connectorName}_read');
      expect(preview).toBeDefined();
    });

    it('should not execute without ENABLE_REAL_EXECUTION', async () => {
      const approved = {
        actionId: '${connectorName}_create',
        params: {},
        requestedBy: 'user',
        requestedAt: BASE_TIME,
        approvedBy: 'admin',
        approvedAt: BASE_TIME,
        approvalReason: 'Test',
        queueId: 'queue_001',
      };
      const receipt = await ${Name}Actions.execute(approved);
      // With ENABLE_REAL_EXECUTION=false, should queue not execute
      expect(receipt.status).toBe('queued');
    });
  });

  describe('${Name} Reader (GAMMA Pattern)', () => {
    let reader: ${Name}Reader;

    beforeEach(() => {
      reader = new ${Name}Reader();
    });

    it('should start empty', () => {
      expect(reader.count()).toBe(0);
    });

    it('should store and retrieve resource', () => {
      const resource = {
        id: 'res_001',
        name: 'Test',
        createdAt: BASE_TIME,
      };
      reader.set('res_001', resource);
      const retrieved = reader.get('res_001');
      expect(retrieved?.id).toBe('res_001');
    });

    it('should get all resources', () => {
      reader.set('r1', { id: 'r1', name: 'A', createdAt: BASE_TIME });
      reader.set('r2', { id: 'r2', name: 'B', createdAt: BASE_TIME });
      expect(reader.all()).toHaveLength(2);
    });

    it('should filter resources', () => {
      reader.set('r1', { id: 'r1', name: 'Alpha', createdAt: BASE_TIME });
      reader.set('r2', { id: 'r2', name: 'Beta', createdAt: BASE_TIME });
      const found = reader.filter(r => r.name.startsWith('A'));
      expect(found).toHaveLength(1);
      expect(found[0].name).toBe('Alpha');
    });

    it('should get summary deterministically', () => {
      reader.set('r1', { id: 'r1', name: 'A', createdAt: BASE_TIME });
      const summary1 = reader.getSummary(BASE_TIME);
      const summary2 = reader.getSummary(BASE_TIME);
      expect(summary1).toEqual(summary2);
    });

    it('should not use Date.now() internally', () => {
      // Calling all time-based methods with explicit time
      const summary = reader.getSummary(BASE_TIME);
      const recent = reader.getRecent(BASE_TIME);
      expect(summary).toBeDefined();
      expect(recent).toBeDefined();
    });
  });
});
`;

const indexTemplate = `/**
 * ${Name} Connector — Barrel Export
 * Generated by connector:scaffold
 */

export { ${Name}OAuth } from './oauth-adapter';
export { ${Name}Client } from './api-client';
export { ${Name}Parser } from './resource-parser';
export type { ${Name}Resource } from './resource-parser';
export { ${Name}Actions } from './action-set';
`;

// ─── File Generation ───────────────────────────────────────────────────────────

function writeFile(filePath: string, content: string): void {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  if (fs.existsSync(filePath)) {
    console.log(`  ⚠️  Already exists (skipping): ${path.relative(ROOT, filePath)}`);
    return;
  }
  fs.writeFileSync(filePath, content, 'utf-8');
  console.log(`  ✅ Created: ${path.relative(ROOT, filePath)}`);
}

console.log(`\n${'═'.repeat(55)}`);
console.log(`  GAMMA CONNECTOR SCAFFOLD`);
console.log(`  Connector: ${connectorName}`);
console.log(`  Service:   ${serviceName}`);
console.log(`  Base URL:  ${baseUrl}`);
console.log('═'.repeat(55) + '\n');

writeFile(path.join(CONNECTOR_DIR, 'oauth-adapter.ts'), oauthAdapterTemplate);
writeFile(path.join(CONNECTOR_DIR, 'api-client.ts'), apiClientTemplate);
writeFile(path.join(CONNECTOR_DIR, 'resource-parser.ts'), resourceParserTemplate);
writeFile(path.join(CONNECTOR_DIR, 'action-set.ts'), actionSetTemplate);
writeFile(path.join(CONNECTOR_DIR, 'index.ts'), indexTemplate);
writeFile(path.join(GAMMA_DIR, `${connectorName}-reader.ts`), readerTemplate);
writeFile(path.join(APP_DIR, 'page.tsx'), dashboardTemplate);
writeFile(path.join(TEST_DIR, `${connectorName}.test.ts`), testTemplate);

const docContent = `# ${serviceName} Connector\n\n**Status**: SCAFFOLDED\n**Generated**: ${new Date().toISOString()}\n\nThis connector was generated by \`connector:scaffold\`.\n\nImplement the 4 adapter files to activate:\n\n1. \`lib/connectors/${connectorName}/oauth-adapter.ts\`\n2. \`lib/connectors/${connectorName}/api-client.ts\`\n3. \`lib/connectors/${connectorName}/resource-parser.ts\`\n4. \`lib/connectors/${connectorName}/action-set.ts\`\n\nSee \`docs/platform/CONNECTOR_DEVELOPER_GUIDE.md\` for full instructions.\n`;
writeFile(path.join(DOCS_DIR, `${connectorName}.md`), docContent);

console.log('\n' + '─'.repeat(55));
console.log(`  ✅ Scaffold complete for '${connectorName}'`);
console.log(`  Next: implement the 4 adapter files`);
console.log(`  Then: npm test -- tests/connectors/${connectorName}.test.ts`);
console.log('─'.repeat(55) + '\n');
