import { RuntimeKernelRegistry, RuntimeUnit } from './types'

const FIXED_TIMESTAMP = 1751990400000

const runtimeUnits: RuntimeUnit[] = [
  {
    id: 'ru-001',
    name: 'Document Creation Engine',
    type: 'action',
    status: 'ready',
    executionMode: 'preview',
    requiresApproval: true,
    safetyLevel: 'high',
    createdAt: FIXED_TIMESTAMP,
    lastUpdated: FIXED_TIMESTAMP,
  },
  {
    id: 'ru-002',
    name: 'Email Draft Composer',
    type: 'action',
    status: 'ready',
    executionMode: 'preview',
    requiresApproval: true,
    safetyLevel: 'critical',
    createdAt: FIXED_TIMESTAMP,
    lastUpdated: FIXED_TIMESTAMP,
  },
  {
    id: 'ru-003',
    name: 'Social Post Generator',
    type: 'action',
    status: 'approved',
    executionMode: 'preview',
    requiresApproval: true,
    safetyLevel: 'high',
    createdAt: FIXED_TIMESTAMP,
    lastUpdated: FIXED_TIMESTAMP,
  },
  {
    id: 'ru-004',
    name: 'Plan Synthesis Workflow',
    type: 'workflow',
    status: 'ready',
    executionMode: 'simulated',
    requiresApproval: true,
    safetyLevel: 'high',
    createdAt: FIXED_TIMESTAMP,
    lastUpdated: FIXED_TIMESTAMP,
  },
  {
    id: 'ru-005',
    name: 'Task Assignment Queue',
    type: 'task',
    status: 'pending',
    executionMode: 'staged',
    requiresApproval: true,
    safetyLevel: 'medium',
    createdAt: FIXED_TIMESTAMP,
    lastUpdated: FIXED_TIMESTAMP,
  },
  {
    id: 'ru-006',
    name: 'Calendar Event Blocker',
    type: 'action',
    status: 'blocked',
    executionMode: 'preview',
    requiresApproval: true,
    safetyLevel: 'medium',
    createdAt: FIXED_TIMESTAMP,
    lastUpdated: FIXED_TIMESTAMP,
  },
  {
    id: 'ru-007',
    name: 'Report Generation Pipeline',
    type: 'workflow',
    status: 'ready',
    executionMode: 'preview',
    requiresApproval: true,
    safetyLevel: 'high',
    createdAt: FIXED_TIMESTAMP,
    lastUpdated: FIXED_TIMESTAMP,
  },
  {
    id: 'ru-008',
    name: 'Approval Chain Orchestrator',
    type: 'approval',
    status: 'approved',
    executionMode: 'simulated',
    requiresApproval: false,
    safetyLevel: 'critical',
    createdAt: FIXED_TIMESTAMP,
    lastUpdated: FIXED_TIMESTAMP,
  },
  {
    id: 'ru-009',
    name: 'Audit Event Logger',
    type: 'audit',
    status: 'ready',
    executionMode: 'preview',
    requiresApproval: false,
    safetyLevel: 'critical',
    createdAt: FIXED_TIMESTAMP,
    lastUpdated: FIXED_TIMESTAMP,
  },
  {
    id: 'ru-010',
    name: 'Safety Policy Enforcer',
    type: 'approval',
    status: 'ready',
    executionMode: 'preview',
    requiresApproval: false,
    safetyLevel: 'critical',
    createdAt: FIXED_TIMESTAMP,
    lastUpdated: FIXED_TIMESTAMP,
  },
]

export const getRuntimeKernelMockData = (): RuntimeKernelRegistry => ({
  id: 'runtime-kernel-001',
  version: '1.0.0',
  status: 'operational',
  runtimeUnits,
  metrics: {
    runtimeScore: 92,
    registeredRuntimeUnits: runtimeUnits.length,
    executionPreviewCount: 156,
    safetyScore: 98,
    approvalCoverage: 85,
    auditabilityScore: 94,
    healthScore: 93,
  },
  lastSync: FIXED_TIMESTAMP,
})
